program_id: press_microwave_button
targets: {}
program:
  kind: segment
  name: press_button
  steps:
    kind: invoke
    call:
      kind: registered
      call_id: simulation.articulation_link_press
      arguments:
        target: microwave_button
