# ----------------------------------------------------------------------------
# Copyright (c) 2021-2025 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

import torch

from embodichain.lab.gym.envs import EmbodiedEnv, EmbodiedEnvCfg
from embodichain.lab.gym.utils.registration import register_env
from embodichain.utils import logger

__all__ = ["ParallelRolloutEnv"]


@register_env("ParallelRollout-v1", max_episode_steps=600)
class ParallelRolloutEnv(EmbodiedEnv):
    """A demo environment

    Args:
        EmbodiedEnv (_type_): _description_
    """

    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)

    def create_demo_action_list(self, *args, **kwargs):
        """
        Create a demonstration action list for the current task.

        Returns:
            list: A list of demo actions generated by the task.
        """
        action_list = []
        for i in range(100):
            action = self.action_space.sample()
            action = torch.as_tensor(action, dtype=torch.float32, device=self.device)

            init_pose = self.robot.get_qpos()
            action = (
                init_pose
                + torch.rand_like(action, dtype=torch.float32, device=self.device) * 0.2
                - 0.1
            )
            action_list.append(action)

        return action_list
