# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

"""Versioned declarative Expert Program schema, compiler, and runtime types."""

from __future__ import annotations

from .cfg import (
    EXPERT_PROGRAM_SCHEMA_VERSION,
    EXPERT_PROGRAM_SCHEMA_VERSION_V2,
    MAX_DECLARATIVE_DEPTH,
    MAX_DECLARATIVE_NODES,
    MAX_EXPANDED_CALLS,
    MAX_PROGRAM_DEPTH,
    MAX_PROGRAM_NODES,
    MAX_REPEAT_COUNT,
    SUPPORTED_EXPERT_PROGRAM_SCHEMA_VERSIONS,
    BarrierCfg,
    CyclicPoseTargetCfg,
    DeclarativeCfgValue,
    ExpertProgramCfg,
    ExpertProgramIntegrationCfg,
    HandOverCfg,
    InvokeCfg,
    ObjectNearTargetValidatorCfg,
    OperateArticulationCfg,
    ParallelCfg,
    PickCfg,
    PlaceCfg,
    PoseCfg,
    PostPolicyCfg,
    ProgramNodeCfg,
    RegisteredSemanticCallCfg,
    RepeatCfg,
    SegmentCfg,
    SemanticCallCfg,
    SequenceCfg,
    TargetCfg,
    TargetRefCfg,
    ValidatorCfg,
    WaitStablePostCfg,
)
from .decoder import (
    ConfigPath,
    ConfigPathPart,
    ExpertProgramConfigError,
    ExpertProgramDecodeError,
    ExpertProgramValidationContext,
    ExpertProgramValidationError,
    SceneReferenceRole,
    decode_expert_program,
    render_config_path,
    validate_expert_program,
)
from .loader import (
    MAX_EXPERT_PROGRAM_BYTES,
    load_expert_program,
    loads_expert_program_json,
    parse_expert_program_json,
)
from .bridge import (
    AcceptedRuntimeCommandObserver,
    AtomicDemoBridge,
    BufferedGymCommandSink,
    DemoBridgeError,
    EnvironmentStepClock,
    EnvironmentStepTimingError,
    GymPlanningObservationProvider,
    RuntimeCommandFrameEncoder,
    RuntimeTransportActionEncoder,
    SegmentPostPolicyMetadataPort,
    SegmentPostPolicyPort,
    SegmentPostPolicyResultPort,
    SegmentValidatorMetadataPort,
    SegmentValidatorPort,
    UnsupportedRuntimeTransportError,
)
from .compiler import (
    CompiledBarrier,
    CompiledParallelBlock,
    CompiledParallelBranch,
    CompiledPostPolicy,
    CompiledProgram,
    CompiledProgramAnalysis,
    CompiledProgramCall,
    CompiledProgramSegment,
    CompiledProgramValidator,
    CompiledRepeatFrame,
    CompiledTargetSelection,
    ExpertProgramCompileError,
    ExpertProgramCompiler,
    ExpertProgramSceneResolver,
    MaterializedCompiledProgram,
    SceneRegistryProgramResolver,
)
from .environment import (
    AcceptedRuntimeCommandObserverFactory,
    ExpertProgramEnvironmentAdapter,
    ExpertProgramEnvironmentFactory,
    ExpertProgramEnvironmentMixin,
    ExpertProgramRuntimeAssembly,
    PlanningObservationPort,
)
from .simulation import (
    AntipodalGraspAffordanceBinding,
    ArticulationOperationAffordanceBinding,
    ArticulationOperationTargetBinding,
    ControlPartCommandPreset,
    ControlPartEndpointBinding,
    ControlPartResourceBinding,
    RobotResourceBinding,
    SimulationArticulationBinding,
    SimulationArticulationLinkBinding,
    SimulationRigidObjectBinding,
    SimulationResourceEndpointBinding,
    SimulationRobotResourceBinding,
    SimulationRobotSkillProfileBinding,
    SimulationSceneBinding,
)
from .simulation_environment import (
    ControlCommandStateEvidenceTracker,
    MotionGeneratorFactory,
    SharedTickSceneProvider,
    SimulationExpertProgramEnvironment,
    SimulationExpertProgramFactory,
    SimulationPlanningObservationProvider,
    create_simulation_expert_program_adapter,
)
from .simulation_policies import SimulationSegmentPolicyPort

__all__ = [
    "AcceptedRuntimeCommandObserver",
    "AcceptedRuntimeCommandObserverFactory",
    "AntipodalGraspAffordanceBinding",
    "ArticulationOperationAffordanceBinding",
    "ArticulationOperationTargetBinding",
    "AtomicDemoBridge",
    "BarrierCfg",
    "BufferedGymCommandSink",
    "ConfigPath",
    "ConfigPathPart",
    "CompiledBarrier",
    "CompiledParallelBlock",
    "CompiledParallelBranch",
    "CompiledPostPolicy",
    "CompiledProgram",
    "CompiledProgramAnalysis",
    "CompiledProgramCall",
    "CompiledProgramSegment",
    "CompiledProgramValidator",
    "CompiledRepeatFrame",
    "CompiledTargetSelection",
    "ControlCommandStateEvidenceTracker",
    "ControlPartCommandPreset",
    "ControlPartEndpointBinding",
    "ControlPartResourceBinding",
    "CyclicPoseTargetCfg",
    "DeclarativeCfgValue",
    "DemoBridgeError",
    "EXPERT_PROGRAM_SCHEMA_VERSION",
    "EXPERT_PROGRAM_SCHEMA_VERSION_V2",
    "EnvironmentStepClock",
    "EnvironmentStepTimingError",
    "ExpertProgramCfg",
    "ExpertProgramCompileError",
    "ExpertProgramCompiler",
    "ExpertProgramConfigError",
    "ExpertProgramDecodeError",
    "ExpertProgramEnvironmentAdapter",
    "ExpertProgramEnvironmentFactory",
    "ExpertProgramEnvironmentMixin",
    "ExpertProgramIntegrationCfg",
    "ExpertProgramRuntimeAssembly",
    "ExpertProgramSceneResolver",
    "ExpertProgramValidationContext",
    "ExpertProgramValidationError",
    "HandOverCfg",
    "GymPlanningObservationProvider",
    "InvokeCfg",
    "MAX_DECLARATIVE_DEPTH",
    "MAX_DECLARATIVE_NODES",
    "MAX_EXPANDED_CALLS",
    "MAX_EXPERT_PROGRAM_BYTES",
    "MAX_PROGRAM_DEPTH",
    "MAX_PROGRAM_NODES",
    "MAX_REPEAT_COUNT",
    "MaterializedCompiledProgram",
    "MotionGeneratorFactory",
    "ObjectNearTargetValidatorCfg",
    "OperateArticulationCfg",
    "ParallelCfg",
    "PickCfg",
    "PlaceCfg",
    "PlanningObservationPort",
    "PoseCfg",
    "PostPolicyCfg",
    "ProgramNodeCfg",
    "RegisteredSemanticCallCfg",
    "RepeatCfg",
    "RobotResourceBinding",
    "RuntimeCommandFrameEncoder",
    "RuntimeTransportActionEncoder",
    "SceneReferenceRole",
    "SceneRegistryProgramResolver",
    "SegmentPostPolicyMetadataPort",
    "SegmentPostPolicyPort",
    "SegmentPostPolicyResultPort",
    "SegmentCfg",
    "SegmentValidatorMetadataPort",
    "SegmentValidatorPort",
    "SemanticCallCfg",
    "SequenceCfg",
    "SharedTickSceneProvider",
    "SimulationArticulationBinding",
    "SimulationArticulationLinkBinding",
    "SimulationExpertProgramEnvironment",
    "SimulationExpertProgramFactory",
    "SimulationPlanningObservationProvider",
    "SimulationRigidObjectBinding",
    "SimulationResourceEndpointBinding",
    "SimulationRobotResourceBinding",
    "SimulationRobotSkillProfileBinding",
    "SimulationSceneBinding",
    "SimulationSegmentPolicyPort",
    "SUPPORTED_EXPERT_PROGRAM_SCHEMA_VERSIONS",
    "TargetCfg",
    "TargetRefCfg",
    "UnsupportedRuntimeTransportError",
    "ValidatorCfg",
    "WaitStablePostCfg",
    "create_simulation_expert_program_adapter",
    "decode_expert_program",
    "load_expert_program",
    "loads_expert_program_json",
    "parse_expert_program_json",
    "render_config_path",
    "validate_expert_program",
]
