# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from embodichain.toolkits.scaffold.naming import (
    default_env_class,
    default_gym_id,
    validate_gym_id,
    validate_package_name,
    validate_snake,
)

Target = Literal["inrepo", "extension"]
Workflow = Literal["demo", "rl", "config-only"]
InrepoCategory = Literal["tableware", "rl", "special"]
RobotPreset = Literal["cobot_magic", "ur5_minimal"]


INREPO_CATEGORIES = ("tableware", "rl", "special")


@dataclass
class TaskSpec:
    """Specification for generating a new task environment."""

    task_snake: str
    workflow: Workflow
    target: Target = "inrepo"

    gym_id: str | None = None
    task_class: str | None = None
    description: str = ""

    category: InrepoCategory = "tableware"
    project_name: str | None = None
    package_name: str | None = None
    output_dir: Path | None = None

    robot_preset: RobotPreset = "cobot_magic"
    max_episode_steps: int = 300
    max_episodes: int = 5
    num_envs: int = 1

    with_rl_config: bool = False
    reward_style: Literal["json", "python"] = "json"
    include_test: bool = True
    dry_run: bool = False
    force: bool = False
    run_black: bool = True
    init_git: bool = False

    repo_root: Path = field(default_factory=lambda: Path(__file__).resolve().parents[3])

    def __post_init__(self) -> None:
        self.task_snake = validate_snake(self.task_snake)
        if self.target == "inrepo" and self.category not in INREPO_CATEGORIES:
            raise ValueError(
                f"category must be one of {INREPO_CATEGORIES}, got {self.category!r}"
            )
        if self.workflow == "rl" and self.target == "inrepo":
            self.category = "rl"
        if self.gym_id is None:
            self.gym_id = default_gym_id(self.task_snake)
        else:
            self.gym_id = validate_gym_id(self.gym_id)
        if self.task_class is None:
            self.task_class = default_env_class(self.task_snake)
        else:
            if not self.task_class.endswith("Env"):
                raise ValueError(
                    f"task_class should end with 'Env', got {self.task_class!r}"
                )
        if not self.description:
            self.description = f"{self.task_class} task environment (generated by embodichain-new-task)."
        if self.target == "extension":
            if self.package_name is None:
                self.package_name = self.task_snake
            validate_package_name(self.package_name)
            if self.project_name is None:
                self.project_name = self.package_name.replace("_", "-")
            if self.output_dir is None:
                self.output_dir = Path.cwd() / self.project_name
            else:
                self.output_dir = Path(self.output_dir).resolve()
        else:
            self.output_dir = self.repo_root

        if self.workflow == "rl":
            self.with_rl_config = True

    @property
    def module_name(self) -> str:
        return self.task_snake

    def task_py_path(self) -> Path:
        if self.target == "extension":
            assert self.package_name is not None
            return (
                self.output_dir / self.package_name / "tasks" / f"{self.task_snake}.py"
            )
        return (
            self.repo_root
            / "embodichain"
            / "lab"
            / "gym"
            / "envs"
            / "tasks"
            / self.category
            / f"{self.task_snake}.py"
        )

    def gym_json_path(self) -> Path:
        if self.target == "extension":
            return self.output_dir / "configs" / self.task_snake / "gym.json"
        if self.workflow == "rl":
            return (
                self.repo_root
                / "configs"
                / "agents"
                / "rl"
                / self.task_snake
                / "gym_config.json"
            )
        return self.repo_root / "configs" / "gym" / self.task_snake / "gym.json"

    def test_py_path(self) -> Path | None:
        if not self.include_test:
            return None
        if self.target == "extension":
            return self.output_dir / "tests" / f"test_{self.task_snake}.py"
        return (
            self.repo_root
            / "tests"
            / "gym"
            / "envs"
            / "tasks"
            / f"test_{self.task_snake}.py"
        )

    def tasks_init_path(self) -> Path:
        if self.target == "extension":
            assert self.package_name is not None
            return self.output_dir / self.package_name / "tasks" / "__init__.py"
        return (
            self.repo_root
            / "embodichain"
            / "lab"
            / "gym"
            / "envs"
            / "tasks"
            / "__init__.py"
        )

    def is_new_extension_project(self) -> bool:
        if self.target != "extension" or self.output_dir is None:
            return False
        return not (self.output_dir / "pyproject.toml").exists()

    def all_output_paths(self) -> list[Path]:
        paths = [self.task_py_path(), self.gym_json_path()]
        if test := self.test_py_path():
            paths.append(test)
        if self.target == "extension" and self.is_new_extension_project():
            assert self.package_name is not None
            pkg = self.output_dir / self.package_name
            paths.extend(
                [
                    pkg / "__init__.py",
                    pkg / "VERSION",
                    self.output_dir / "pyproject.toml",
                    self.output_dir / "README.md",
                    self.output_dir / "LICENSE",
                    self.output_dir / ".gitignore",
                    self.output_dir / "VERSION",
                    self.output_dir / "scripts" / "run_env.py",
                    pkg / "data" / "__init__.py",
                    pkg / "data" / "constants.py",
                    pkg / "utils" / "__init__.py",
                    pkg / "tasks" / "__init__.py",
                ]
            )
        return paths

    def import_path(self) -> str:
        if self.target == "extension":
            assert self.package_name is not None
            return f"{self.package_name}.tasks.{self.task_snake}"
        return f"embodichain.lab.gym.envs.tasks.{self.category}.{self.task_snake}"

    def tasks_init_import_line(self) -> str:
        """Import line written into ``tasks/__init__.py``."""
        if self.target == "extension":
            return f"from .{self.task_snake} import {self.task_class}"
        return f"from {self.import_path()} import {self.task_class}"
