# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

"""
Example: Using Language Support for VLA Training with Online Data Streaming

This example demonstrates how to configure and use the hierarchical language
support for Vision-Language-Action (VLA) model training.
"""

import torch
from torch.utils.data import DataLoader

from embodichain.agents.engine.data import OnlineDataEngine, OnlineDataEngineCfg
from embodichain.agents.datasets.online_data import OnlineDataset
from embodichain.lab.gym.envs.managers import (
    LanguageCfg,
    LanguageManager,
    HierarchicalLanguageData,
)


# Example 1: Basic ODS with Language Support (File-based)
def example_ods_with_language_file():
    """Set up ODS with language descriptions loaded from a YAML file."""

    # Language configuration
    language_cfg = {
        "mode": "tokens",
        "hierarchy_levels": ["task", "subtask", "primitive"],
        "max_tokens": 512,
        "tokenizer": "gpt2",
        "language_source": "file",
        "language_config_path": "configs/language/tasks_example.yaml",
        "max_instructions_per_level": 5,
    }

    # ODS engine configuration
    engine_cfg = OnlineDataEngineCfg(
        buffer_size=16,
        max_episode_steps=300,
        state_dim=14,
        gym_config={
            "id": "EmbodiedEnv-v1",
            "env": {"robot": {...}},
            # ... other env config
        },
        language_cfg=language_cfg,  # Enable language support
    )

    # Create and start the engine
    engine = OnlineDataEngine(engine_cfg)
    engine.start()

    # Create dataset with language support
    dataset = OnlineDataset(engine, chunk_size=64, batch_size=8)

    # Create DataLoader
    loader = DataLoader(
        dataset,
        batch_size=None,  # Batch mode (dataset handles batching)
        num_workers=0,
        collate_fn=OnlineDataset.passthrough_collate_fn,
    )

    # Training loop
    for batch in loader:
        # Access different data modalities
        obs = batch["obs"]  # Vision and proprioception
        actions = batch["actions"]  # Robot actions
        language = batch["language"]  # Hierarchical language data

        # Access language at different hierarchy levels
        task_tokens = language[
            "task_level_tokens"
        ]  # [batch, chunk, max_instr, max_tokens]
        task_mask = language["task_level_attention_mask"]

        subtask_tokens = language["subtask_level_tokens"]
        subtask_mask = language["subtask_level_attention_mask"]

        primitive_tokens = language["primitive_level_tokens"]
        primitive_mask = language["primitive_level_attention_mask"]

        # Use for VLA training
        # train_step(obs, language, actions)


# Example 2: Environment-Based Language Generation
def example_env_based_language():
    """Set up ODS with language generated by the environment."""

    language_cfg = {
        "mode": "tokens",
        "hierarchy_levels": ["task", "subtask"],
        "max_tokens": 256,
        "tokenizer": "gpt2",
        "language_source": "env",  # Environment generates language
    }

    engine_cfg = OnlineDataEngineCfg(
        buffer_size=16,
        max_episode_steps=300,
        state_dim=14,
        gym_config={...},
        language_cfg=language_cfg,
    )

    engine = OnlineDataEngine(engine_cfg)
    engine.start()

    # Your environment should implement:
    # - get_task_language(task_id, context) -> HierarchicalLanguageData
    # - Or have a task_description attribute


# Example 3: Template-Based Language
def example_template_based_language():
    """Set up ODS with template-based language generation."""

    language_cfg = {
        "mode": "tokens",
        "hierarchy_levels": ["task", "subtask"],
        "max_tokens": 256,
        "tokenizer": "gpt2",
        "language_source": "template",
        "templates": {
            "pick_and_place": {
                "task": "Pick up the {color} {object} and place it {location}.",
                "subtasks": [
                    "Move to the {color} {object}.",
                    "Grasp the {color} {object}.",
                    "Move {location}.",
                    "Release the {object}.",
                ],
            }
        },
        "variables": {
            "color": "red",
            "object": "block",
            "location": "in the blue basket",
        },
    }

    engine_cfg = OnlineDataEngineCfg(
        buffer_size=16,
        max_episode_steps=300,
        state_dim=14,
        gym_config={...},
        language_cfg=language_cfg,
    )

    engine = OnlineDataEngine(engine_cfg)
    engine.start()


# Example 4: Using Language Manager Directly
def example_language_manager():
    """Use LanguageManager to tokenize and manage language data."""

    cfg = LanguageCfg(
        mode="tokens",
        hierarchy_levels=["task", "subtask", "primitive"],
        max_tokens=512,
        tokenizer="gpt2",
    )

    # Create a simple mock environment
    class MockEnv:
        task_name = "pick_and_place"
        task_description = "Pick up the red block and place it in the basket."

    env = MockEnv()
    manager = LanguageManager(cfg, env)

    # Create hierarchical language data
    language_data = manager.create_hierarchical_language_data(
        task_texts="Pick up the red block and place it in the basket.",
        subtask_texts=[
            "Move to the red block.",
            "Grasp the red block.",
            "Move to the basket.",
            "Release the block.",
        ],
        primitive_texts=[
            "Close gripper.",
            "Move up.",
            "Move right.",
            "Open gripper.",
        ],
        change_points=[0, 10, 20, 30],
    )

    # Convert to buffer format
    buffer_format = language_data.to_buffer_format(cfg)

    # Access tokenized data
    task_tokens = buffer_format["task_level_tokens"]  # [max_instructions, max_tokens]
    task_mask = buffer_format["task_level_attention_mask"]


# Example 5: Dynamic Chunk Size with Language
def example_dynamic_chunk_language():
    """Use dynamic chunk sizes with language support."""

    from embodichain.agents.datasets.sampler import UniformChunkSampler

    language_cfg = {
        "mode": "tokens",
        "hierarchy_levels": ["task"],
        "max_tokens": 256,
        "tokenizer": "gpt2",
        "language_source": "file",
        "language_config_path": "configs/language/tasks_example.yaml",
    }

    engine_cfg = OnlineDataEngineCfg(
        buffer_size=16,
        max_episode_steps=300,
        state_dim=14,
        gym_config={...},
        language_cfg=language_cfg,
    )

    engine = OnlineDataEngine(engine_cfg)
    engine.start()

    # Dynamic chunk size sampler
    chunk_sampler = UniformChunkSampler(low=32, high=96)

    # Dataset with dynamic chunk size
    dataset = OnlineDataset(
        engine,
        chunk_size=chunk_sampler,
        batch_size=8,
    )

    loader = DataLoader(
        dataset,
        batch_size=None,
        collate_fn=OnlineDataset.passthrough_collate_fn,
    )

    for batch in loader:
        # Batch shape is [batch_size, chunk_size, ...]
        # Chunk dimension varies each iteration
        print(f"Batch chunk size: {batch.shape[1]}")

        # Language tokens are broadcast across all timesteps
        language = batch["language"]
        task_tokens = language[
            "task_level_tokens"
        ]  # [batch_size, chunk_size, max_instr, max_tokens]


# Example 6: Custom Environment with Language
def example_custom_env_with_language():
    """Example of a custom environment implementing language generation."""

    from embodichain.lab.gym.envs import EmbodiedEnv, EmbodiedEnvCfg

    class MyTaskEnv(EmbodiedEnv):
        """Custom environment that provides language descriptions."""

        def __init__(self, cfg, **kwargs):
            super().__init__(cfg, **kwargs)
            self.task_name = "my_custom_task"

        def get_task_language(self, task_id, context=None):
            """Generate hierarchical language for the current task."""
            return self.language_manager.create_hierarchical_language_data(
                task_texts="Complete the custom manipulation task.",
                subtask_texts=[
                    "Approach the object.",
                    "Grasp the object.",
                    "Move to target location.",
                    "Release the object.",
                ],
                primitive_texts=[
                    "Move forward.",
                    "Close gripper.",
                    "Move up.",
                    "Move right.",
                    "Open gripper.",
                ],
            )

    # Configuration with language
    env_cfg = EmbodiedEnvCfg(
        robot={...},
        language={
            "mode": "tokens",
            "hierarchy_levels": ["task", "subtask", "primitive"],
            "max_tokens": 512,
            "tokenizer": "gpt2",
            "language_source": "env",  # Environment will generate language
        },
        init_rollout_buffer=True,
    )

    env = MyTaskEnv(env_cfg)


if __name__ == "__main__":
    print("Language Support Examples for VLA Training")
    print("=" * 50)
    print("\nAvailable examples:")
    print("1. example_ods_with_language_file() - File-based language")
    print("2. example_env_based_language() - Environment-based language")
    print("3. example_template_based_language() - Template-based language")
    print("4. example_language_manager() - Direct LanguageManager usage")
    print("5. example_dynamic_chunk_language() - Dynamic chunk sizes")
    print("6. example_custom_env_with_language() - Custom environment")
    print("\nRun any example function to see it in action.")
