# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

from __future__ import annotations

from types import SimpleNamespace

import pytest
import torch

import embodichain.lab.sim.planners.trapezoidal_planner as trapezoidal_module
from embodichain.lab.sim.planners.trapezoidal_planner import (
    TrapezoidalPlanner,
    TrapezoidalPlanOptions,
    _build_double_s_profile,
    _build_scalar_profile,
    _compress_collinear_waypoints,
    _plan_linear_profiles,
)
from embodichain.lab.sim.planners.utils import PlanState, TrajectorySampleMethod


@pytest.mark.parametrize("profile", ["trapezoidal", "double_s"])
def test_profiles_reach_endpoints_and_limits(profile: str) -> None:
    waypoints = torch.tensor(
        [
            [[0.0, 0.0], [1.0, -0.5]],
            [[0.2, -0.1], [0.4, 0.7]],
        ],
        dtype=torch.float64,
    )
    velocity_limit = 0.6
    acceleration_limit = 1.2
    options = TrapezoidalPlanOptions(
        profile=profile,
        constraints={
            "velocity": velocity_limit,
            "acceleration": acceleration_limit,
            "jerk": 4.0,
        },
        sample_method=TrajectorySampleMethod.QUANTITY,
        sample_interval=401,
    )

    result = _plan_linear_profiles(waypoints, options)

    assert result.success.all()
    assert torch.allclose(result.positions[:, 0], waypoints[:, 0])
    assert torch.allclose(result.positions[:, -1], waypoints[:, -1])
    assert float(result.velocities.abs().max()) <= velocity_limit + 1e-9
    assert float(result.accelerations.abs().max()) <= acceleration_limit + 1e-9
    assert torch.all(result.dt >= 0.0)
    assert torch.allclose(result.duration, result.dt.sum(dim=1))


def test_triangular_profile_handles_zero_duration_cruise_boundary() -> None:
    waypoints = torch.tensor([[[0.0], [1.0]]], dtype=torch.float64)
    options = TrapezoidalPlanOptions(
        profile="trapezoidal",
        constraints={"velocity": 1.0, "acceleration": 1.0, "jerk": 1.0},
        sample_interval=3,
        backend="torch",
    )

    result = _plan_linear_profiles(waypoints, options)

    assert torch.allclose(
        result.positions[0, :, 0],
        torch.tensor([0.0, 0.5, 1.0], dtype=torch.float64),
    )
    assert torch.allclose(
        result.velocities[0, :, 0],
        torch.tensor([0.0, 1.0, 0.0], dtype=torch.float64),
    )


def test_double_s_has_continuous_acceleration_samples() -> None:
    waypoints = torch.tensor([[[0.0], [1.0]]], dtype=torch.float64)
    options = TrapezoidalPlanOptions(
        profile="double_s",
        constraints={"velocity": 0.8, "acceleration": 1.0, "jerk": 2.0},
        sample_interval=2001,
    )

    result = _plan_linear_profiles(waypoints, options)
    acceleration_jump = torch.diff(result.accelerations[0, :, 0]).abs().max()

    assert float(acceleration_jump) < 0.01


def test_double_s_respects_sampled_jerk_limit() -> None:
    jerk_limit = 2.0
    waypoints = torch.tensor([[[0.0], [1.0]]], dtype=torch.float64)
    options = TrapezoidalPlanOptions(
        profile="double_s",
        constraints={
            "velocity": 0.8,
            "acceleration": 1.0,
            "jerk": jerk_limit,
        },
        sample_interval=4001,
    )

    result = _plan_linear_profiles(waypoints, options)
    sampled_jerk = torch.diff(result.accelerations[0, :, 0]) / result.dt[0, 1:]

    assert float(sampled_jerk.abs().max()) <= jerk_limit + 1e-9


@pytest.mark.parametrize(
    ("distance", "velocity", "acceleration", "jerk", "expected_duration"),
    [
        (1.0, 0.2, 0.5, 2.0, 5.7065),
        (0.01, 0.2, 0.5, 2.0, 0.5483947163846388),
        (0.1, 1.0, 1.0, 1.0, 1.4898240646067618),
        (1.0, 1.0, 1.0, 1.0, 3.214067124738025),
    ],
)
def test_double_s_duration_matches_reference_golden_values(
    distance: float,
    velocity: float,
    acceleration: float,
    jerk: float,
    expected_duration: float,
) -> None:
    """Match values generated by the reference trajectory implementation."""
    waypoints = torch.tensor([[[0.0], [distance]]], dtype=torch.float64)
    options = TrapezoidalPlanOptions(
        profile="double_s",
        constraints={
            "velocity": velocity,
            "acceleration": acceleration,
            "jerk": jerk,
        },
        sample_interval=101,
        backend="torch",
    )

    result = _plan_linear_profiles(waypoints, options)

    assert result.duration.item() == pytest.approx(expected_duration, abs=1e-12)


def test_double_s_multi_waypoint_samples_match_reference() -> None:
    """Cover segment lookup and derivative scaling with C++ golden samples."""
    waypoints = torch.tensor(
        [[[0.0, 0.0], [0.4, -0.2], [0.1, 0.3]]], dtype=torch.float64
    )
    options = TrapezoidalPlanOptions(
        profile="double_s",
        constraints={"velocity": 0.6, "acceleration": 1.2, "jerk": 3.0},
        sample_interval=5,
        backend="torch",
    )
    result = _plan_linear_profiles(waypoints, options)

    assert result.duration.item() == pytest.approx(3.407298139310801, abs=1e-12)
    assert torch.allclose(result.positions[0, 0], waypoints[0, 0])
    boundary_matches = torch.isclose(
        result.positions[0], waypoints[0, 1], atol=1e-8, rtol=0.0
    ).all(dim=1)
    assert boundary_matches.any()
    boundary_index = boundary_matches.nonzero()[0, 0]
    assert torch.allclose(result.positions[0, boundary_index], waypoints[0, 1])
    assert torch.allclose(result.positions[0, -1], waypoints[0, -1])
    assert torch.allclose(
        result.velocities[0, 0], torch.zeros(2, dtype=result.velocities.dtype)
    )
    assert torch.allclose(
        result.velocities[0, boundary_index],
        torch.zeros(2, dtype=result.velocities.dtype),
        atol=1e-8,
    )
    assert torch.allclose(
        result.velocities[0, -1], torch.zeros(2, dtype=result.velocities.dtype)
    )
    assert torch.all(result.dt[0, 1:] >= 0.0)


def test_double_s_short_move_breakpoints_match_reference() -> None:
    """Lock the discrete acceleration-reduction branch to C++ behavior."""
    distance = 0.01
    velocity_limit = torch.tensor([[0.2 / distance]], dtype=torch.float64)
    acceleration_limit = torch.tensor([[0.5 / distance]], dtype=torch.float64)
    jerk_limit = torch.tensor([[2.0 / distance]], dtype=torch.float64)
    profile = _build_double_s_profile(velocity_limit, acceleration_limit, jerk_limit)
    expected_unscaled_durations = torch.tensor(
        [
            0.13286025,
            0.0057620338537815,
            0.13286025,
            0.0,
            0.13286025,
            0.0057620338537815,
            0.13286025,
        ],
        dtype=torch.float64,
    )

    assert torch.allclose(
        profile.durations[0, 0], expected_unscaled_durations, atol=1e-14
    )


def test_per_joint_limits_are_projected_onto_path() -> None:
    velocity_limits = torch.tensor([0.25, 0.8], dtype=torch.float64)
    acceleration_limits = torch.tensor([0.5, 1.5], dtype=torch.float64)
    waypoints = torch.tensor([[[0.0, 0.0], [0.5, 1.0]]], dtype=torch.float64)
    options = TrapezoidalPlanOptions(
        constraints={
            "velocity": velocity_limits,
            "acceleration": acceleration_limits,
            "jerk": torch.tensor([1.0, 3.0], dtype=torch.float64),
        },
        sample_interval=1001,
    )

    result = _plan_linear_profiles(waypoints, options)

    assert torch.all(result.velocities.abs().amax(dim=(0, 1)) <= velocity_limits)
    assert torch.all(result.accelerations.abs().amax(dim=(0, 1)) <= acceleration_limits)


@pytest.mark.parametrize("profile", ["trapezoidal", "double_s"])
def test_warp_backend_matches_torch_on_cpu(profile: str) -> None:
    pytest.importorskip("warp")
    waypoints = torch.tensor(
        [
            [[0.0, 0.0], [0.4, -0.2], [0.1, 0.3]],
            [[0.1, -0.1], [0.2, 0.5], [0.8, 0.2]],
        ],
        dtype=torch.float32,
    )
    common = {
        "profile": profile,
        "constraints": {"velocity": 0.6, "acceleration": 1.2, "jerk": 3.0},
        "sample_interval": 257,
    }

    torch_result = _plan_linear_profiles(
        waypoints, TrapezoidalPlanOptions(**common, backend="torch")
    )
    warp_result = _plan_linear_profiles(
        waypoints, TrapezoidalPlanOptions(**common, backend="warp")
    )

    assert torch.allclose(warp_result.positions, torch_result.positions, atol=1e-5)
    assert torch.allclose(warp_result.velocities, torch_result.velocities, atol=1e-5)
    assert torch.allclose(
        warp_result.accelerations, torch_result.accelerations, atol=1e-5
    )
    assert torch.equal(warp_result.dt, torch_result.dt)


@pytest.mark.parametrize("profile", ["trapezoidal", "double_s"])
def test_warp_profile_construction_matches_torch(profile: str) -> None:
    pytest.importorskip("warp")
    velocity = torch.tensor([[0.0, 0.2, 1.0], [0.6, 4.0, 0.1]])
    acceleration = torch.tensor([[1.0, 0.5, 1.0], [1.2, 2.0, 0.3]])
    jerk = torch.tensor([[2.0, 2.0, 1.0], [3.0, 8.0, 0.5]])

    torch_profile = _build_scalar_profile(
        profile_name=profile,
        velocity_limit=velocity,
        acceleration_limit=acceleration,
        jerk_limit=jerk,
        backend="torch",
    )
    warp_profile = _build_scalar_profile(
        profile_name=profile,
        velocity_limit=velocity,
        acceleration_limit=acceleration,
        jerk_limit=jerk,
        backend="warp",
    )

    for torch_value, warp_value in zip(
        (
            torch_profile.durations,
            torch_profile.positions,
            torch_profile.velocities,
            torch_profile.accelerations,
            torch_profile.jerks,
        ),
        (
            warp_profile.durations,
            warp_profile.positions,
            warp_profile.velocities,
            warp_profile.accelerations,
            warp_profile.jerks,
        ),
        strict=True,
    ):
        assert torch.allclose(warp_value, torch_value, atol=1e-5, rtol=1e-5)


def test_many_segment_path_preserves_constraints_and_endpoints() -> None:
    waypoint_count = 129
    parameter = torch.linspace(0.0, 4.0, waypoint_count, dtype=torch.float64)
    path = torch.stack(
        [parameter, torch.sin(parameter), 0.5 * torch.cos(parameter)], dim=-1
    )
    waypoints = torch.stack([path, path + torch.tensor([0.1, -0.2, 0.3])])
    options = TrapezoidalPlanOptions(
        profile="double_s",
        constraints={"velocity": 0.7, "acceleration": 1.4, "jerk": 4.0},
        sample_interval=1025,
        backend="torch",
    )

    result = _plan_linear_profiles(waypoints, options)

    assert torch.allclose(result.positions[:, 0], waypoints[:, 0])
    assert torch.allclose(result.positions[:, -1], waypoints[:, -1])
    assert float(result.velocities.abs().max()) <= 0.7 + 1e-9
    assert float(result.accelerations.abs().max()) <= 1.4 + 1e-9


def test_explicit_warp_backend_rejects_float64() -> None:
    waypoints = torch.tensor([[[0.0], [1.0]]], dtype=torch.float64)
    options = TrapezoidalPlanOptions(backend="warp")

    with pytest.raises(ValueError, match="requires float32"):
        _plan_linear_profiles(waypoints, options)


def test_multiple_segments_stop_at_internal_waypoint() -> None:
    waypoints = torch.tensor([[[0.0], [0.5], [-0.25]]], dtype=torch.float64)
    options = TrapezoidalPlanOptions(
        profile="trapezoidal",
        constraints={"velocity": 0.4, "acceleration": 0.8, "jerk": 2.0},
        sample_interval=801,
    )

    result = _plan_linear_profiles(waypoints, options)
    nearest = torch.argmin((result.positions[0, :, 0] - 0.5).abs())

    assert result.positions[0, nearest, 0] == pytest.approx(0.5, abs=1e-5)
    assert result.velocities[0, nearest, 0] == pytest.approx(0.0, abs=2e-3)


def test_collinear_compression_removes_only_same_direction_points() -> None:
    waypoints = torch.tensor(
        [
            [[0.0, 0.0], [0.25, 0.0], [0.5, 0.0], [1.0, 0.0]],
            [[0.0, 0.0], [0.5, 0.0], [0.25, 0.0], [1.0, 0.0]],
        ]
    )

    compressed = _compress_collinear_waypoints(waypoints, tolerance=1e-5)

    assert compressed.shape == (2, 4, 2)
    assert torch.equal(compressed[0, 0], waypoints[0, 0])
    assert torch.equal(compressed[0, 1], waypoints[0, -1])
    assert torch.equal(compressed[1], waypoints[1])


def test_disabling_waypoint_stops_shortens_dense_straight_path() -> None:
    waypoints = torch.linspace(0.0, 1.0, 21, dtype=torch.float64).reshape(1, 21, 1)
    stopped = TrapezoidalPlanOptions(
        profile="double_s",
        sample_interval=501,
        stop_at_waypoints=True,
    )
    continuous = TrapezoidalPlanOptions(
        profile="double_s",
        sample_interval=501,
        stop_at_waypoints=False,
    )

    stopped_result = _plan_linear_profiles(waypoints, stopped)
    continuous_result = _plan_linear_profiles(waypoints, continuous)

    assert continuous_result.duration < stopped_result.duration
    assert torch.allclose(continuous_result.positions[:, 0], waypoints[:, 0])
    assert torch.allclose(continuous_result.positions[:, -1], waypoints[:, -1])


def test_collinear_compression_pads_batch_rows_with_final_point() -> None:
    waypoints = torch.tensor(
        [
            [[0.0], [0.25], [0.5], [1.0]],
            [[0.0], [0.5], [0.25], [1.0]],
        ]
    )

    compressed = _compress_collinear_waypoints(waypoints, tolerance=1e-5)

    assert compressed.shape == waypoints.shape
    assert torch.all(compressed[0, 1:] == 1.0)
    assert torch.equal(compressed[1], waypoints[1])


def test_duplicate_waypoint_run_preserves_adjacent_corner() -> None:
    waypoints = torch.tensor([[[0.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 1.0]]])

    compressed = _compress_collinear_waypoints(waypoints, tolerance=1e-5)

    assert torch.equal(compressed[0, :3], waypoints[0, (0, 1, 3)])


def test_quantity_sampling_includes_exact_internal_waypoint_and_stop() -> None:
    waypoints = torch.tensor([[[0.0, 0.0], [1.0, 0.0], [1.0, 1.0]]])
    options = TrapezoidalPlanOptions(sample_interval=4)

    result = _plan_linear_profiles(waypoints, options)

    waypoint_matches = torch.isclose(
        result.positions[0], waypoints[0, 1], atol=1e-6, rtol=0.0
    ).all(dim=1)
    assert waypoint_matches.any()
    waypoint_index = waypoint_matches.nonzero()[0, 0]
    assert torch.allclose(result.velocities[0, waypoint_index], torch.zeros(2))


def test_quantity_sampling_rejects_fewer_samples_than_waypoints() -> None:
    waypoints = torch.tensor([[[0.0], [1.0], [2.0]]])

    with pytest.raises(ValueError, match="at least one sample per retained waypoint"):
        _plan_linear_profiles(waypoints, TrapezoidalPlanOptions(sample_interval=2))


def test_stationary_path_returns_zero_duration_hold() -> None:
    waypoints = torch.full((2, 3, 4), 0.25)
    options = TrapezoidalPlanOptions(sample_interval=10)

    result = _plan_linear_profiles(waypoints, options)

    assert result.success.all()
    assert torch.all(result.positions == 0.25)
    assert torch.count_nonzero(result.velocities) == 0
    assert torch.count_nonzero(result.accelerations) == 0
    assert torch.count_nonzero(result.dt) == 0


def test_stationary_fast_path_skips_profile_construction(monkeypatch) -> None:
    def fail_if_called(*args, **kwargs) -> None:
        raise AssertionError("stationary paths must not construct a profile")

    monkeypatch.setattr(
        trapezoidal_module, "_build_trapezoidal_profile", fail_if_called
    )
    waypoints = torch.full((2, 3, 4), 0.25)

    result = _plan_linear_profiles(
        waypoints, TrapezoidalPlanOptions(sample_interval=10)
    )

    assert result.positions.shape == (2, 10, 4)
    assert torch.count_nonzero(result.dt) == 0


def test_minimum_duration_slows_trajectory_without_changing_path() -> None:
    requested_duration = 5.0
    waypoints = torch.tensor([[[0.0, 0.0], [0.3, -0.2]]], dtype=torch.float64)
    base = TrapezoidalPlanOptions(profile="double_s", sample_interval=301)
    slowed = TrapezoidalPlanOptions(
        profile="double_s",
        sample_interval=301,
        minimum_duration=requested_duration,
    )

    base_result = _plan_linear_profiles(waypoints, base)
    slowed_result = _plan_linear_profiles(waypoints, slowed)

    assert slowed_result.duration.item() == pytest.approx(requested_duration)
    assert torch.allclose(base_result.positions, slowed_result.positions, atol=1e-6)
    assert slowed_result.velocities.abs().max() < base_result.velocities.abs().max()


def test_stationary_path_can_hold_for_minimum_duration() -> None:
    requested_duration = 2.5
    waypoints = torch.full((1, 2, 3), 0.25)
    options = TrapezoidalPlanOptions(
        sample_interval=11,
        minimum_duration=requested_duration,
    )

    result = _plan_linear_profiles(waypoints, options)

    assert result.duration.item() == pytest.approx(requested_duration)
    assert torch.all(result.positions == 0.25)
    assert torch.count_nonzero(result.velocities) == 0


def test_stationary_time_sampling_preserves_requested_hold_duration() -> None:
    waypoints = torch.full((2, 2, 3), 0.25)
    options = TrapezoidalPlanOptions(
        sample_method=TrajectorySampleMethod.TIME,
        sample_interval=0.2,
        minimum_duration=0.5,
    )

    result = _plan_linear_profiles(waypoints, options)

    assert result.positions.shape == (2, 4, 3)
    assert torch.allclose(result.duration, torch.full((2,), 0.5))
    assert torch.allclose(result.dt[:, 1:], torch.full((2, 3), 0.5 / 3.0))


def test_time_sampling_tail_pads_shorter_rows() -> None:
    waypoints = torch.tensor([[[0.0], [1.0]], [[0.0], [0.1]]])
    options = TrapezoidalPlanOptions(
        sample_method=TrajectorySampleMethod.TIME,
        sample_interval=0.05,
    )

    result = _plan_linear_profiles(waypoints, options)

    assert result.positions.shape[0] == 2
    assert torch.allclose(result.positions[:, -1], waypoints[:, -1])
    assert result.duration[0] > result.duration[1]
    assert torch.count_nonzero(result.dt[1] == 0.0) > 1


@pytest.mark.parametrize(
    ("kwargs", "message"),
    [
        ({"profile": "unknown"}, "profile"),
        ({"sample_interval": 1}, "at least 2"),
        ({"sample_interval": 2.5}, "integer"),
        ({"minimum_duration": float("inf")}, "minimum_duration"),
        ({"collinearity_tolerance": 1.0}, "collinearity_tolerance"),
        ({"backend": "unknown"}, "backend"),
        ({"constraints": {"velocity": 1.0}}, "missing required keys"),
    ],
)
def test_options_reject_invalid_configuration(kwargs: dict, message: str) -> None:
    with pytest.raises(ValueError, match=message):
        TrapezoidalPlanOptions(**kwargs)


def test_rejects_nonpositive_joint_limit() -> None:
    waypoints = torch.tensor([[[0.0], [1.0]]])
    options = TrapezoidalPlanOptions(
        constraints={"velocity": 0.0, "acceleration": 1.0, "jerk": 1.0}
    )

    with pytest.raises(ValueError, match="finite positive"):
        _plan_linear_profiles(waypoints, options)


def test_planner_adapts_batched_plan_states() -> None:
    planner = TrapezoidalPlanner.__new__(TrapezoidalPlanner)
    planner.device = torch.device("cpu")
    planner.cfg = SimpleNamespace(planner_type="trapezoidal")
    states = [
        PlanState.from_qpos(torch.tensor([[0.0, 0.0]])),
        PlanState.from_qpos(torch.tensor([[0.5, -0.25]])),
    ]

    result = planner.plan(states, TrapezoidalPlanOptions(sample_interval=20))

    assert result.positions.shape == (1, 20, 2)
    assert result.dt.shape == (1, 20)
    assert result.is_all_success()
