program_id: twist_microwave_knob
targets: {}
program:
  kind: segment
  name: twist_knob
  steps:
    kind: invoke
    call:
      kind: registered
      call_id: simulation.articulation_link_twist
      arguments:
        target: microwave_knob
